services:
  # Servis 1: PostgreSQL Veritabanı
  db:
    image: postgres:14-alpine
    container_name: book-social-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=book_social_db
      - POSTGRES_USER=kayra
      - POSTGRES_PASSWORD=wqwq2121
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kayra -d book_social_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servis 2: Redis Önbellek Sunucusu
  redis:
    image: redis:7-alpine
    container_name: book-social-redis
    ports:
      - "6379:6379"

  # Servis 3: Bizim Spring Boot Uygulamamız
  app:
    build: .
    container_name: book-social-app
    depends_on: 
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      # --- Veritabanı Ayarları ---
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/book_social_db
      - SPRING_DATASOURCE_USERNAME=kayra
      - SPRING_DATASOURCE_PASSWORD=wqwq2121
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate # <-- BU BİLİNÇLİ OLARAK 'create' (Geçici)
      - SPRING_FLYWAY_SCHEMAS=book_social
      
      # --- Redis Ayarları ---
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis
      
     

volumes:
  postgres_data: