-- Sequence'ler (Otomatik artan ID'ler için)
CREATE SEQUENCE book_social.authors_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE book_social.books_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE book_social.refresh_token_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE book_social.reviews_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE book_social.users_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;

-- Tablolar
CREATE TABLE book_social.authors (
	birth_year int4 NOT NULL,
	create_time timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	country varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT authors_pkey PRIMARY KEY (id)
);

CREATE TABLE book_social.users (
	create_time timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(255) NULL,
	"role" varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);

CREATE TABLE book_social.books (
	publication_year int4 NOT NULL,
	rating numeric(3, 1) NULL,
	review_count int4 NULL,
	author_id int8 NOT NULL,
	create_time timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title varchar(255) NOT NULL,
	-- google_books_id alanı artık yok
	CONSTRAINT books_pkey PRIMARY KEY (id),
	CONSTRAINT fkfjixh2vym2cvfj3ufxj91jem7 FOREIGN KEY (author_id) REFERENCES book_social.authors(id)
);

CREATE TABLE book_social.refresh_token (
	create_time timestamp(6) NULL,
	expire_date timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NULL,
	refresh_token varchar(255) NULL,
	CONSTRAINT refresh_token_pkey PRIMARY KEY (id),
	CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES book_social.users(id)
);

CREATE TABLE book_social.reviews (
	rating int4 NULL,
	book_id int8 NOT NULL,
	create_time timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	"content" varchar(255) NULL,
	CONSTRAINT reviews_pkey PRIMARY KEY (id),
	CONSTRAINT fk6a9k6xvev80se5rreqvuqr7f9 FOREIGN KEY (book_id) REFERENCES book_social.books(id),
	CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES book_social.users(id)
);